# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeff Tang's AI on Mobile Blog
email: jeff@ailabby.com
description: "Marriage of AI and Mobile: Problems and Solutions"
topics: "AI Anywhere, Anytime"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeffxtang.github.io" # the base hostname & protocol for your site
twitter_username: jeffxtang
github_username:  jeffxtang

# Build settings
#markdown: redcarpet
markdown: kramdown
future: false
